services:
  app:
    image: 'contratos'
    build: .
    ports:
      - "8081:8080"
    #mem_limit: 512m
    #memswap_limit: 512m
    #cpus: 1.0
    environment:
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      #- JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=55 -XX:+UseSerialGC -Xss512k -XX:MaxMetaspaceSize=128m -XX:NativeMemoryTracking=summary
    env_file:
      - .env