version: '2'
services:
  app:
    image: 'foo'
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql
      - SPRING_DATASOURCE_USERNAME=foo
      - SPRING_DATASOURCE_PASSWORD=foo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - foo:foo
    environment:
      - POSTGRES_DB=foo
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=foo
  # Clinte db
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - foo:foo