# Desativa o cache do Thymeleaf em desenvolvimento
spring.thymeleaf.cache=false

spring.web.resources.static-locations=file:src/main/resources/static/

#server.error.include-stacktrace=on-param
#logging.level.org.hibernate=ERROR
spring.datasource.hikari.data-source-properties.prepareThreshold=0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
