# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuração da porta
server.port=${PORT:8080}
server.address=0.0.0.0

#spring.devtools.restart.additional-paths=src/main/resources # app.props usa essa config. removida por causar lentidão no server.

# Desativa o cache do Thymeleaf em desenvolvimento
spring.thymeleaf.cache=false

# default value = true
spring.jpa.open-in-view=true

#server.error.include-stacktrace=on-param
#logging.level.org.hibernate=ERROR
spring.datasource.hikari.data-source-properties.prepareThreshold=0
