# Perfil ativo
spring.profiles.active=dev

# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuração da porta
server.port=${PORT:8080}
server.address=0.0.0.0

# JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#server.error.include-stacktrace=never
#logging.level.org.hibernate=ERROR
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Garanta que o DevTools esteja ativo para restart/livereload
spring.devtools.restart.enabled=true
#spring.devtools.livereload.enabled=true deprecated no 

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SUPABASE_ISSUER_URI}
supabase.anon.key=${SUPABASE_ANON_KEY}
supabase.url=${SUPABASE_URL}

gdrive.file.url=${GDRIVE_FILE_URL}

spring.config.import=optional:file:.env[.properties]?charset=utf-8
app.security.allowed-ips=${ALLOWED_IPS:127.0.0.1}

#
server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2
server.tomcat.max-connections=50