package com.projeto.teste.ProjetoTestes.model;

public enum Departamento {
  DAPGS("DEPARTAMENTO DE ADMINISTRAÇÃO PÚBLICA E GESTÃO SOCIAL"),
  DACT("DEPARTAMENTO DE ANALISES CLÍNICAS E TOXICOLÓGICAS"),
  DANT("DEPARTAMENTO DE ANTROPOLOGIA"),
  DARQ("DEPARTAMENTO DE ARQUITETURA"),
  DART("DEPARTAMENTO DE ARTES"),
  DBF("DEPARTAMENTO DE BIOFÍSICA E FARMACOLOGIA"),
  DBQ("DEPARTAMENTO DE BIOQUÍMICA"),
  DBZ("DEPARTAMENTO DE BOTÂNICA E ZOOLOGIA"),
  DBEZ("DEPARTAMENTO DE BOTÂNICA ECOLOGIA E ZOOLOGIA"),
  DCI("DEPARTAMENTO DE CIÊNCIA DA INFORMAÇÃO"),
  DCADM("DEPARTAMENTO DE CIÊNCIAS ADMINISTRATIVAS"),
  DCAC("DEPARTAMENTO DE CIÊNCIAS ATMOSFÉRICAS E CLIMÁTICAS"),
  DCC("DEPARTAMENTO DE CIÊNCIAS CONTÁBEIS"),
  DCEA("DEPARTAMENTO DE CIÊNCIAS EXATAS E APLICADAS"),
  DCS("DEPARTAMENTO DE CIÊNCIAS SOCIAIS"),
  DCSH("DEPARTAMENTO DE CIÊNCIAS SOCIAIS E HUMANAS"),
  DCSH_CERES("DEPARTAMENTO DE CIÊNCIAS SOCIAIS E HUMANAS DO CENTRO DE ENSINO SUPERIOR DO SERIDÓ - CERES"),
  DCIR("DEPARTAMENTO DE CIRURGIA"),
  DCT_CERES("DEPARTAMENTO DE COMPUTAÇÃO E TECNOLOGIA DO CENTRO DE ENSINO SUPERIOR DO SERIDÓ - CERES"),
  DCOM("DEPARTAMENTO DE COMUNICAÇÃO SOCIAL"),
  DDCA("DEPARTAMENTO DE DEMOGRAFIA E CIÊNCIAS ATUARIAIS"),
  DD_CERES("DEPARTAMENTO DE DIREITO DO CENTRO DE ENSINO SUPERIOR DO SERIDÓ - CERES"),
  DDIR_PRIV("DEPARTAMENTO DE DIREITO PRIVADO"),
  DDIR_PROC("DEPARTAMENTO DE DIREITO PROCESSUAL E PROPEDÊUTICA"),
  DDIR_PUB("DEPARTAMENTO DE DIREITO PÚBLICO"),
  DECO("DEPARTAMENTO DE ECOLOGIA"),
  DECON("DEPARTAMENTO DE ECONOMIA"),
  DEDU("DEPARTAMENTO DE EDUCAÇÃO"),
  DEDU_CERES("DEPARTAMENTO DE EDUCACAO DO CENTRO DE ENSINO SUPERIOR DO SERIDÓ - CERES"),
  DEF("DEPARTAMENTO DE EDUCAÇÃO FÍSICA"),
  DENF("DEPARTAMENTO DE ENFERMAGEM"),
  DEBM("DEPARTAMENTO DE ENGENHARIA BIOMÉDICA"),
  DECIV("DEPARTAMENTO DE ENGENHARIA CIVIL"),
  DECA("DEPARTAMENTO DE ENGENHARIA DE COMPUTAÇÃO E AUTOMAÇÃO"),
  DEPROD("DEPARTAMENTO DE ENGENHARIA DE PRODUÇÃO"),
  DEEL("DEPARTAMENTO DE ENGENHARIA ELÉTRICA"),
  DEMEC("DEPARTAMENTO DE ENGENHARIA MECÂNICA"),
  DEQ("DEPARTAMENTO DE ENGENHARIA QUÍMICA"),
  DETXT("DEPARTAMENTO DE ENGENHARIA TÊXTIL"),
  DEST("DEPARTAMENTO DE ESTATÍSTICA"),
  DFARM("DEPARTAMENTO DE FARMÁCIA"),
  DFILO("DEPARTAMENTO DE FILOSOFIA"),
  DFIS("DEPARTAMENTO DE FÍSICA TEÓRICA E EXPERIMENTAL"),
  DFISIO("DEPARTAMENTO DE FISIOLOGIA"),
  DFISIOP("DEPARTAMENTO DE FISIOTERAPIA"),
  DFONO("DEPARTAMENTO DE FONOAUDIOLOGIA"),
  DFPE("DEPARTAMENTO DE FUNDAMENTOS E POLÍTICAS DA EDUCAÇÃO"),
  DGEO("DEPARTAMENTO DE GEOGRAFIA"),
  DGEO_CERES("DEPARTAMENTO DE GEOGRAFIA DO CENTRO DE ENSINO SUPERIOR DO SERIDÓ - CERES"),
  DHIST("DEPARTAMENTO DE HISTÓRIA"),
  DHIST_CERES("DEPARTAMENTO DE HISTORIA DO CENTRO DE ENSINO SUPERIOR DO SERIDÓ - CERES"),
  DIMAP("DEPARTAMENTO DE INFORMÁTICA E MATEMÁTICA APLICADA"),
  DLET("DEPARTAMENTO DE LETRAS"),
  DLET_CERES("DEPARTAMENTO DE LETRAS DO CENTRO DE ENSINO SUPERIOR DO SERIDÓ - CERES"),
  DLLEM("DEPARTAMENTO DE LÍNGUAS E LITERATURAS ESTRANGEIRAS MODERNAS"),
  DMAT("DEPARTAMENTO DE MATEMÁTICA"),
  DMCL("DEPARTAMENTO DE MEDICINA CLÍNICA"),
  DMIN("DEPARTAMENTO DE MEDICINA INTEGRADA"),
  DMP("DEPARTAMENTO DE MICROBIOLOGIA E PARASITOLOGIA"),
  DMORF("DEPARTAMENTO DE MORFOLOGIA"),
  DNUT("DEPARTAMENTO DE NUTRIÇÃO"),
  DOL("DEPARTAMENTO DE OCEANOGRAFIA E LIMNOLOGIA"),
  DODO("DEPARTAMENTO DE ODONTOLOGIA"),
  DPED("DEPARTAMENTO DE PEDIATRIA"),
  DPP("DEPARTAMENTO DE POLÍTICAS PÚBLICAS"),
  DPEC("DEPARTAMENTO DE PRÁTICAS EDUCACIONAIS E CURRÍCULO"),
  DPSI("DEPARTAMENTO DE PSICOLOGIA"),
  DSC("DEPARTAMENTO DE SAÚDE COLETIVA"),
  DSS("DEPARTAMENTO DE SERVICO SOCIAL"),
  DTG("DEPARTAMENTO DE TOCO-GINECOLOGIA"),
  DTUR("DEPARTAMENTO DE TURISMO"),

  EAJ("ESCOLA AGRÍCOLA DE JUNDIAÍ"),
  ECT("ESCOLA DE CIÊNCIAS E TECNOLOGIA"),
  EMUFRN("ESCOLA DE MÚSICA DA UFRN"),
  ESUFRN("ESCOLA DE SAÚDE DA UFRN"),
  EMCM("ESCOLA MULTICAMPI DE CIÊNCIAS MÉDICAS"),
  FACISA("FACULDADE DE CIÊNCIAS DA SAÚDE DO TRAIRI - FACISA"),
  FELCS("FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOCIAIS DO SERIDÓ - FELCS"),
  IMT("INSTITUTO DE MEDICINA TROPICAL"),
  IQ("INSTITUTO DE QUÍMICA"),
  IMD("INSTITUTO METRÓPOLE DIGITAL"),
  NEI("NÚCLEO DE EDUCAÇÃO DA INFÂNCIA - NEI");

  private final String descricao;

  Departamento(String descricao) {
        this.descricao = descricao;
    }

  public String getDescricao() {
    return descricao;
  }

  @Override
  public String toString() {
    return "Departamento: " + descricao;
  }
}
